package com.unissoft.test.mapper;

import com.unissoft.test.entity.AiLgLdOrc;

public interface AiLgLdOrcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AI_LG_LD_ORC
     *
     * @mbg.generated
     */
    int insert(AiLgLdOrc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AI_LG_LD_ORC
     *
     * @mbg.generated
     */
    int insertSelective(AiLgLdOrc record);
}