package com.unissoft.test.mapper;

import com.unissoft.test.entity.TMxglModel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TMxglModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mxgl_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mxgl_model
     *
     * @mbg.generated
     */
    int insert(TMxglModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mxgl_model
     *
     * @mbg.generated
     */
    int insertSelective(TMxglModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mxgl_model
     *
     * @mbg.generated
     */
    TMxglModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mxgl_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMxglModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mxgl_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMxglModel record);

    List<TMxglModel> selectList();
}