package com.unissoft.test.mapper;

import com.unissoft.test.entity.TsGthl;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TsGthlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_gthl
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_gthl
     *
     * @mbg.generated
     */
    int insert(TsGthl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_gthl
     *
     * @mbg.generated
     */
    int insertSelective(TsGthl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_gthl
     *
     * @mbg.generated
     */
    TsGthl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_gthl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsGthl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_gthl
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsGthl record);

    List<TsGthl> selectList();
}