package com.unissoft.test.mapper;

import com.unissoft.test.entity.TSysPermission;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TSysPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Sys_Permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Sys_Permission
     *
     * @mbg.generated
     */
    int insert(TSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Sys_Permission
     *
     * @mbg.generated
     */
    int insertSelective(TSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Sys_Permission
     *
     * @mbg.generated
     */
    TSysPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Sys_Permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Sys_Permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSysPermission record);
}