package com.unissoft.test.mapper.mysql;

import com.unissoft.test.entity.TSysRole;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TSysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Sys_Role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Sys_Role
     *
     * @mbg.generated
     */
    int insert(TSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Sys_Role
     *
     * @mbg.generated
     */
    int insertSelective(TSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Sys_Role
     *
     * @mbg.generated
     */
    TSysRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Sys_Role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Sys_Role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSysRole record);
}