package com.unissoft.test.entity;

public class AiLgLdOrc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.heatno
     *
     * @mbg.generated
     */
    private String heatno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.stl_grd_cd
     *
     * @mbg.generated
     */
    private String stlGrdCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.maccode
     *
     * @mbg.generated
     */
    private String maccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.in_ste_scr_wgt
     *
     * @mbg.generated
     */
    private String inSteScrWgt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.in_iron_wgt
     *
     * @mbg.generated
     */
    private String inIronWgt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.pro_blow_cnt
     *
     * @mbg.generated
     */
    private String proBlowCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.pro_stl_time
     *
     * @mbg.generated
     */
    private String proStlTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.pro_n
     *
     * @mbg.generated
     */
    private String proN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.pro_ar
     *
     * @mbg.generated
     */
    private String proAr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.pro_lance_position
     *
     * @mbg.generated
     */
    private String proLancePosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.out_c
     *
     * @mbg.generated
     */
    private String outC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.out_p
     *
     * @mbg.generated
     */
    private String outP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.out_s
     *
     * @mbg.generated
     */
    private String outS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.out_outsttemp
     *
     * @mbg.generated
     */
    private String outOutsttemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.out_ste_wgt
     *
     * @mbg.generated
     */
    private String outSteWgt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.heatno
     *
     * @return the value of AI_LG_LD_ORC.heatno
     * @mbg.generated
     */
    public String getHeatno() {
        return heatno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.heatno
     *
     * @param heatno the value for AI_LG_LD_ORC.heatno
     * @mbg.generated
     */
    public void setHeatno(String heatno) {
        this.heatno = heatno == null ? null : heatno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.stl_grd_cd
     *
     * @return the value of AI_LG_LD_ORC.stl_grd_cd
     * @mbg.generated
     */
    public String getStlGrdCd() {
        return stlGrdCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.stl_grd_cd
     *
     * @param stlGrdCd the value for AI_LG_LD_ORC.stl_grd_cd
     * @mbg.generated
     */
    public void setStlGrdCd(String stlGrdCd) {
        this.stlGrdCd = stlGrdCd == null ? null : stlGrdCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.maccode
     *
     * @return the value of AI_LG_LD_ORC.maccode
     * @mbg.generated
     */
    public String getMaccode() {
        return maccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.maccode
     *
     * @param maccode the value for AI_LG_LD_ORC.maccode
     * @mbg.generated
     */
    public void setMaccode(String maccode) {
        this.maccode = maccode == null ? null : maccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.in_ste_scr_wgt
     *
     * @return the value of AI_LG_LD_ORC.in_ste_scr_wgt
     * @mbg.generated
     */
    public String getInSteScrWgt() {
        return inSteScrWgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.in_ste_scr_wgt
     *
     * @param inSteScrWgt the value for AI_LG_LD_ORC.in_ste_scr_wgt
     * @mbg.generated
     */
    public void setInSteScrWgt(String inSteScrWgt) {
        this.inSteScrWgt = inSteScrWgt == null ? null : inSteScrWgt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.in_iron_wgt
     *
     * @return the value of AI_LG_LD_ORC.in_iron_wgt
     * @mbg.generated
     */
    public String getInIronWgt() {
        return inIronWgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.in_iron_wgt
     *
     * @param inIronWgt the value for AI_LG_LD_ORC.in_iron_wgt
     * @mbg.generated
     */
    public void setInIronWgt(String inIronWgt) {
        this.inIronWgt = inIronWgt == null ? null : inIronWgt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.pro_blow_cnt
     *
     * @return the value of AI_LG_LD_ORC.pro_blow_cnt
     * @mbg.generated
     */
    public String getProBlowCnt() {
        return proBlowCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.pro_blow_cnt
     *
     * @param proBlowCnt the value for AI_LG_LD_ORC.pro_blow_cnt
     * @mbg.generated
     */
    public void setProBlowCnt(String proBlowCnt) {
        this.proBlowCnt = proBlowCnt == null ? null : proBlowCnt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.pro_stl_time
     *
     * @return the value of AI_LG_LD_ORC.pro_stl_time
     * @mbg.generated
     */
    public String getProStlTime() {
        return proStlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.pro_stl_time
     *
     * @param proStlTime the value for AI_LG_LD_ORC.pro_stl_time
     * @mbg.generated
     */
    public void setProStlTime(String proStlTime) {
        this.proStlTime = proStlTime == null ? null : proStlTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.pro_n
     *
     * @return the value of AI_LG_LD_ORC.pro_n
     * @mbg.generated
     */
    public String getProN() {
        return proN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.pro_n
     *
     * @param proN the value for AI_LG_LD_ORC.pro_n
     * @mbg.generated
     */
    public void setProN(String proN) {
        this.proN = proN == null ? null : proN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.pro_ar
     *
     * @return the value of AI_LG_LD_ORC.pro_ar
     * @mbg.generated
     */
    public String getProAr() {
        return proAr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.pro_ar
     *
     * @param proAr the value for AI_LG_LD_ORC.pro_ar
     * @mbg.generated
     */
    public void setProAr(String proAr) {
        this.proAr = proAr == null ? null : proAr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.pro_lance_position
     *
     * @return the value of AI_LG_LD_ORC.pro_lance_position
     * @mbg.generated
     */
    public String getProLancePosition() {
        return proLancePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.pro_lance_position
     *
     * @param proLancePosition the value for AI_LG_LD_ORC.pro_lance_position
     * @mbg.generated
     */
    public void setProLancePosition(String proLancePosition) {
        this.proLancePosition = proLancePosition == null ? null : proLancePosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.out_c
     *
     * @return the value of AI_LG_LD_ORC.out_c
     * @mbg.generated
     */
    public String getOutC() {
        return outC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.out_c
     *
     * @param outC the value for AI_LG_LD_ORC.out_c
     * @mbg.generated
     */
    public void setOutC(String outC) {
        this.outC = outC == null ? null : outC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.out_p
     *
     * @return the value of AI_LG_LD_ORC.out_p
     * @mbg.generated
     */
    public String getOutP() {
        return outP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.out_p
     *
     * @param outP the value for AI_LG_LD_ORC.out_p
     * @mbg.generated
     */
    public void setOutP(String outP) {
        this.outP = outP == null ? null : outP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.out_s
     *
     * @return the value of AI_LG_LD_ORC.out_s
     * @mbg.generated
     */
    public String getOutS() {
        return outS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.out_s
     *
     * @param outS the value for AI_LG_LD_ORC.out_s
     * @mbg.generated
     */
    public void setOutS(String outS) {
        this.outS = outS == null ? null : outS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.out_outsttemp
     *
     * @return the value of AI_LG_LD_ORC.out_outsttemp
     * @mbg.generated
     */
    public String getOutOutsttemp() {
        return outOutsttemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.out_outsttemp
     *
     * @param outOutsttemp the value for AI_LG_LD_ORC.out_outsttemp
     * @mbg.generated
     */
    public void setOutOutsttemp(String outOutsttemp) {
        this.outOutsttemp = outOutsttemp == null ? null : outOutsttemp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AI_LG_LD_ORC.out_ste_wgt
     *
     * @return the value of AI_LG_LD_ORC.out_ste_wgt
     * @mbg.generated
     */
    public String getOutSteWgt() {
        return outSteWgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AI_LG_LD_ORC.out_ste_wgt
     *
     * @param outSteWgt the value for AI_LG_LD_ORC.out_ste_wgt
     * @mbg.generated
     */
    public void setOutSteWgt(String outSteWgt) {
        this.outSteWgt = outSteWgt == null ? null : outSteWgt.trim();
    }
}