package com.unissoft.test.entity;

public class Lz_Demo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.heatno
     *
     * @mbg.generated
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.stl_grd_cd
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.maccode
     *
     * @mbg.generated
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AI_LG_LD_ORC.in_ste_scr_wgt
     *
     * @mbg.generated
     */
    private String remark;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}