package com.unissoft.test.entity;

import lombok.Data;

import java.math.BigDecimal;

@Data
public class TGt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.C
     *
     * @mbg.generated
     */
    private BigDecimal C;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Si
     *
     * @mbg.generated
     */
    private BigDecimal Si;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Mn
     *
     * @mbg.generated
     */
    private BigDecimal Mn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.P
     *
     * @mbg.generated
     */
    private BigDecimal P;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.S
     *
     * @mbg.generated
     */
    private BigDecimal S;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Cr
     *
     * @mbg.generated
     */
    private BigDecimal Cr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Ni
     *
     * @mbg.generated
     */
    private BigDecimal Ni;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Cu
     *
     * @mbg.generated
     */
    private BigDecimal Cu;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Rel
     *
     * @mbg.generated
     */
    private BigDecimal Rel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Rm
     *
     * @mbg.generated
     */
    private BigDecimal Rm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.A
     *
     * @mbg.generated
     */
    private BigDecimal A;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Z
     *
     * @mbg.generated
     */
    private BigDecimal Z;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Rel
     *
     * @mbg.generated
     */
    private BigDecimal L_Rel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Rm
     *
     * @mbg.generated
     */
    private BigDecimal L_Rm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.A
     *
     * @mbg.generated
     */
    private BigDecimal L_A;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Z
     *
     * @mbg.generated
     */
    private BigDecimal L_Z;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Rel
     *
     * @mbg.generated
     */
    private BigDecimal NL_Rel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Rm
     *
     * @mbg.generated
     */
    private BigDecimal NL_Rm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.A
     *
     * @mbg.generated
     */
    private BigDecimal NL_A;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gt_0.Z
     *
     * @mbg.generated
     */
    private BigDecimal NL_Z;

}