package com.unissoft.test.entity;

public class TMxglModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mxgl_model.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mxgl_model.MXGLMXLB
     *
     * @mbg.generated
     */
    private String mxglmxlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mxgl_model.MXGLMXMC
     *
     * @mbg.generated
     */
    private String mxglmxmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mxgl_model.MXGLSYFW
     *
     * @mbg.generated
     */
    private String mxglsyfw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mxgl_model.MXGLMXSM
     *
     * @mbg.generated
     */
    private String mxglmxsm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mxgl_model.id
     *
     * @return the value of t_mxgl_model.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mxgl_model.id
     *
     * @param id the value for t_mxgl_model.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mxgl_model.MXGLMXLB
     *
     * @return the value of t_mxgl_model.MXGLMXLB
     * @mbg.generated
     */
    public String getMxglmxlb() {
        return mxglmxlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mxgl_model.MXGLMXLB
     *
     * @param mxglmxlb the value for t_mxgl_model.MXGLMXLB
     * @mbg.generated
     */
    public void setMxglmxlb(String mxglmxlb) {
        this.mxglmxlb = mxglmxlb == null ? null : mxglmxlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mxgl_model.MXGLMXMC
     *
     * @return the value of t_mxgl_model.MXGLMXMC
     * @mbg.generated
     */
    public String getMxglmxmc() {
        return mxglmxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mxgl_model.MXGLMXMC
     *
     * @param mxglmxmc the value for t_mxgl_model.MXGLMXMC
     * @mbg.generated
     */
    public void setMxglmxmc(String mxglmxmc) {
        this.mxglmxmc = mxglmxmc == null ? null : mxglmxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mxgl_model.MXGLSYFW
     *
     * @return the value of t_mxgl_model.MXGLSYFW
     * @mbg.generated
     */
    public String getMxglsyfw() {
        return mxglsyfw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mxgl_model.MXGLSYFW
     *
     * @param mxglsyfw the value for t_mxgl_model.MXGLSYFW
     * @mbg.generated
     */
    public void setMxglsyfw(String mxglsyfw) {
        this.mxglsyfw = mxglsyfw == null ? null : mxglsyfw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mxgl_model.MXGLMXSM
     *
     * @return the value of t_mxgl_model.MXGLMXSM
     * @mbg.generated
     */
    public String getMxglmxsm() {
        return mxglmxsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mxgl_model.MXGLMXSM
     *
     * @param mxglmxsm the value for t_mxgl_model.MXGLMXSM
     * @mbg.generated
     */
    public void setMxglmxsm(String mxglmxsm) {
        this.mxglmxsm = mxglmxsm == null ? null : mxglmxsm.trim();
    }
}