package com.unissoft.test.entity;

import java.math.BigDecimal;

public class TsGthl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_Gthl.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_Gthl.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_Gthl.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_Gthl.value1
     *
     * @mbg.generated
     */
    private BigDecimal value1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_Gthl.value2
     *
     * @mbg.generated
     */
    private BigDecimal value2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_Gthl.id
     *
     * @return the value of ts_Gthl.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_Gthl.id
     *
     * @param id the value for ts_Gthl.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_Gthl.code
     *
     * @return the value of ts_Gthl.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_Gthl.code
     *
     * @param code the value for ts_Gthl.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_Gthl.name
     *
     * @return the value of ts_Gthl.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_Gthl.name
     *
     * @param name the value for ts_Gthl.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_Gthl.value1
     *
     * @return the value of ts_Gthl.value1
     *
     * @mbg.generated
     */
    public BigDecimal getValue1() {
        return value1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_Gthl.value1
     *
     * @param value1 the value for ts_Gthl.value1
     *
     * @mbg.generated
     */
    public void setValue1(BigDecimal value1) {
        this.value1 = value1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_Gthl.value2
     *
     * @return the value of ts_Gthl.value2
     *
     * @mbg.generated
     */
    public BigDecimal getValue2() {
        return value2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_Gthl.value2
     *
     * @param value2 the value for ts_Gthl.value2
     *
     * @mbg.generated
     */
    public void setValue2(BigDecimal value2) {
        this.value2 = value2;
    }
}