package com.unissoft.test.entity;

import lombok.Data;

import java.util.List;

@Data
public class TSysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Sys_User.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Sys_User.userCode
     *
     * @mbg.generated
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Sys_User.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Sys_User.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Sys_User.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Sys_User.id
     *
     * @return the value of t_Sys_User.id
     *
     * @mbg.generated
     */
}