package com.unissoft.test.entity;

import lombok.Data;

@Data
public class TSysPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Sys_Permission.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Sys_Permission.pName
     *
     * @mbg.generated
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Sys_Permission.pType
     *
     * @mbg.generated
     */
    private String ptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Sys_Permission.pCode
     *
     * @mbg.generated
     */
    private String pcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Sys_Permission.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Sys_Permission.sort
     *
     * @mbg.generated
     */
    private String sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Sys_Permission.id
     *
     * @return the value of t_Sys_Permission.id
     *
     * @mbg.generated
     */
}